#!/usr/bin/env php
<?php
declare(strict_types=1);

require __DIR__ . '/../vendor/autoload.php';

class Hi
{
    /**
     * @param string $name
     * @return void
     * todo 第一引数にIO的なものを渡す？ WriteHandle ReadHandle ErrorHandle
     * todo Aura.Cliで書き換えたい
     **/
    public function handle(string $name): void
    {
        echo 'Hi ' . $name . '!' . PHP_EOL;
    }
}

class Hello
{
    /**
     * @param string $name
     * @return void
     **/
    public function handle(string $name): void
    {
        echo 'Hello ' . $name . '!' . PHP_EOL;
    }
}

class GoodBye
{
    /**
     * @param string $name
     * @return void
     **/
    public function handle(string $name): void
    {
        echo 'GoodBye ' . $name . '!' . PHP_EOL;
    }
}


class Fuga
{
    /**
     * @param string $name 名前
     * @param int|null $test テストオプション
     * @param bool|null $debug デバッグモード
     */
    public function handle(string $name, ?int $test = null, ?bool $debug = false): void
    {
        var_dump([
            'command' => self::class,
            'name' => $name,
            'test' => $test,
            'debug' => $debug
        ]);
    }
}

$definition = [
    Hi::class,
    'hello' => Hello::class,
    'bye' => GoodBye::class,
    'fuga' => Fuga::class,
];

$app = (new \N1215\MicroCli\ApplicationFactory())->make($definition);


$app->run($argv);



